from typing import Protocol

from app.observability.trace import NodeTraceEvent, RunTrace


class TraceRepository(Protocol):
    def record_run(self, run_trace: RunTrace) -> None: ...

    def record_node_event(self, event: NodeTraceEvent) -> None: ...

    def get_run(self, run_id: str) -> RunTrace: ...

    def list_node_events(self, run_id: str) -> list[NodeTraceEvent]: ...

    def clear(self) -> None: ...
